### ISSUE TITLE
No module named 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by xifen523** [djamahl99/findnpropagate#6]
` python extract_pseudo_labels.py --cfg_file cfgs/nuscenes_box_seeker_proposals.yaml --folder ../data/pseudo_labels/nuscenes_box_seeker_proposals/
augmentor {'DISABLE_AUG_LIST': ['placeholder', 'random_world_flip', 'random_world_rotation', 'random_world_scaling', 'random_world_translation'], 'AUG_CONFIG_LIST': None}
aug list None
2024-12-05 16:13:08,402   INFO  Loading NuScenes dataset
2024-12-05 16:13:08,431   INFO  Total samples for NuScenes dataset: 323
{'lq': 0.0, 'uq': 0.25, 'cq': 1.0, 'iou_w': 1.0, 'nms_normal': 1.0, 'dst_w': 0.0, 'dns_w': 1.0, 'min_cam_iou': 0.3, 'score_thr': 0.45, 'nms_2d': 0.4, 'nms_3d': 0.0, 'clamp_bottom': 1, 'num_sizes': 1}
will be generating a total of 60 in each frustum
{'lq': 0.0, 'uq': 0.25, 'iou_w': 1.0, 'dst_w': 0.0, 'dns_w': 1.0, 'min_cam_iou': 0.3, 'size_min': 0.957, 'size_max': 1.2, 'ry_min': 0.0, 'ry_max': 3.141592653589793, 'cq': 1.0, 'num_mags': 6, 'max_dist': 50, 'num_sizes': 1, 'num_rotations': 10, 'topk': 1}
preds_path PreprocessedGLIP
Traceback (most recent call last):
  File "extract_pseudo_labels.py", line 152, in <module>
    main()
  File "extract_pseudo_labels.py", line 67, in main
    model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=inf_set)
  File "/root/autodl-tmp/findnpropagate/pcdet/models/__init__.py", line 17, in build_network
    model = build_detector(
  File "/root/autodl-tmp/findnpropagate/pcdet/models/detectors/__init__.py", line 42, in build_detector
    model = __all__[model_cfg.NAME](
  File "/root/autodl-tmp/findnpropagate/pcdet/models/detectors/transfusion.py", line 8, in __init__
    self.module_list = self.build_networks()
  File "/root/autodl-tmp/findnpropagate/pcdet/models/detectors/detector3d_template.py", line 67, in build_networks
    module, model_info_dict = getattr(self, 'build_%s' % module_name)(
  File "/root/autodl-tmp/findnpropagate/pcdet/models/detectors/detector3d_template.py", line 149, in build_dense_head
    dense_head_module = dense_heads.__all__[self.model_cfg.DENSE_HEAD.NAME](
  File "/root/autodl-tmp/findnpropagate/pcdet/models/dense_heads/frustum_proposals_v1.py", line 257, in __init__
    self.image_detector = PreprocessedGLIP(class_names=class_names)
  File "/root/autodl-tmp/findnpropagate/pcdet/models/preprocessed_detector.py", line 20, in __init__
    self.glip_bboxes = torch.load(self.glip_bbox_file)
  File "/root/miniconda3/envs/ov/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/ov/lib/python3.8/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/ov/lib/python3.8/site-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'maskrcnn_benchmark'`

**Comment by djamahl99** [comment]
Hi, sorry for late reply.

Just wondering, are you loading one of the checkpoints? It seems I might have used pickle and so it is expecting some modules I had installed to be there to unpickle. You might have to create a script and load just the state_model from the checkpoint.

Let me know if you get any further errors.
